export { default as Blog } from "./blog/Blog"
export { default as Features } from "./features/Features"
export { default as Header } from "./header/Header"
export { default as WhatGp3 } from "./whatGp3/WhatGp3"
export { default as Possibility} from "./possibility/Possibility"
export { default as Footer } from "./footer/Footer"